services:
  - type: web
    name: task-management-backend
    env: node
    buildCommand: npm install
    startCommand: npm run migrate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: task_management_db
          property: connectionString
      - key: FRONTEND_URL
        value: https://task-management-frontend-six-self.vercel.app

databases:
  - name: task_management_db
    databaseName: task_management
    user: task_management_user
    plan: free
